### ISSUE TITLE
Gibt es noch "draw"? eigentlich gibt es nur noch gain wisdom right? 

### ISSUE THREAD

**Issue by QriouZz** [DecentralCardGame/cardobject#26]
Patrick meint, das wäre in der grammatik noch falsch
Soll es autodraw geben bei 10 wisdom?

**Comment by nlsui** [comment]
HQs werden als eigenständiger Typ in die Grammatik hinzugefügt (Eigene Manipulations, usw).
HQs erhalten die Eigenschaft WisdomPool. Diese wird zu Beginn des Zuges um den Wisdomwert des HQs erhöht.
Andere Karten können mittels TargetEffect diesen Wert Manipulieren. Lässt ein Effect den WisdomPool über 10 wachsen,
werden automatisch als Teil dieses Effekts solange 10 vom Pool abgezogen und dafür eine Karte gezogen, bis der Wert unter 10 ist.

**Comment by QriouZz** [comment]
Gibt es trotzdem "draw" als Anweisung auf einer Karte? oder ist draw das Keyword für Produce 10 Wisdom
