### ISSUE TITLE
Kann es andere Cantrips als Brainstorm geben?

### ISSUE THREAD

**Issue by QriouZz** [DecentralCardGame/cardobject#27]
Das deck hat ja keine order. Ich kann kein tutor auf top bauen right?
Kann man "Look at 3 Cards of your Deck, put 1 into your hand" machen?

**Comment by patrickwieth** [comment]
eigentlich sollte das kein problem sein, solange es oki ist, wenn die 2 nicht gezogenen karten wieder random ins deck kommen

**Comment by nlsui** [comment]
no permission by cardobject necessary
