### ISSUE TITLE
Player-Condition does not work

### ISSUE THREAD

**Issue by patrickwieth** [DecentralCardGame/cardobject#31]
Player-Condition does not allow "no condition", but picking an PlayerIntCondition also does not work:

↵↵↵↵Conditions implemented by not exactly one option↵↵↵↵↵PlayerIntProperty:  not available↵IntVariableName:  not available

![Unbenannt](https://user-images.githubusercontent.com/10943178/103283980-3e308f00-49da-11eb-9012-e1d064d1f962.png)

Reproduce:
![ArcoLinux_2020-12-29_13-33-54](https://user-images.githubusercontent.com/10943178/103284085-95cefa80-49da-11eb-9831-729420facd3e.png)

create a card that bounces other cards on spawn

**Comment by QriouZz** [comment]
blub
