### ISSUE TITLE
Add rarities

### ISSUE THREAD

**Issue by lxgr-linux** [DecentralCardGame/cardobject#69]
Add rarities to the card type, so they can be used for collections.

**Comment by patrickwieth** [comment]
rarities are not added to a card without the context of a set

so the card has a rarity only after addition to a set, where the set determines the rarity for each card

**Comment by lxgr-linux** [comment]
But therefore the cardobject should provide a rarity attribute and a rarity enum.

**Comment by patrickwieth** [comment]
we discussed this, it is better to put it in the cardobject because otherwise the game client or the frontend need to make further look ups
