### ISSUE TITLE
auto generate rulesText

### ISSUE THREAD

**Issue by patrickwieth** [DecentralCardGame/cardobject#74]
the idea for this feature is that the frontend no longer generates rulesText but rather the cardobject creates proper RulesText

**Comment by patrickwieth** [comment]
maybe this is useful

https://github.com/DecentralCardGame/frontend/blob/master/src/components/utils/utils.js#L62

https://github.com/DecentralCardGame/frontend/blob/master/src/components/utils/utils.js#L132

**Comment by nlsui** [comment]
Should the rulestext be in the cardobject?

Pro:
 - same rulestext everywhere
Con:
 - rulestext in blockchain (storage)
 - not every application needs it but gets it anyways

**Comment by nlsui** [comment]
moved here DecentralCardGame/gameclient/issues/254
