### ISSUE TITLE
maximum of 8 keywords

### ISSUE THREAD

**Issue by patrickwieth** [DecentralCardGame/cardobject#75]
a card should have no more than 8 keywords, so for example:

Ability:
OnSpawn - Produce 3 => 2 Keywords
Avenge - Kill TARGET. Harm 3, Void ALL => 4 Keywords
both of the above => 6 keywords

the same goes for action cards, but there are only effects that count into keywords...

**Comment by nlsui** [comment]
DecentralCardGame/gameclient/issues/253

**Comment by nlsui** [comment]
In the validation this is easy to handle. However for the schema it is not possible.
I have to set the maximum of an array during schema generation,
so its not possible to shorten the array of the second ability based on userinputs in the first.
This means wrong userinputs have to be prevented in the frontend, validation can happen in the cardobject.

**Comment by nlsui** [comment]
agreed with @patrickwieth I adjust the validation, he is responsible for frontend
