### ISSUE TITLE
Cardtype for Target

### ISSUE THREAD

**Issue by patrickwieth** [DecentralCardGame/cardobject#84]
<img width="312" alt="image" src="https://user-images.githubusercontent.com/10943178/210779750-fcc3a7da-194c-459c-9bd2-d3eb47a2cb4f.png">

Target does not know a Cardtype, sad. 
If there were different Targets in the cardobject, for example AnyTarget, HQTarget, EntityTarget, PlaceTarget, PlaceHQTarget (naming can be changed), then awesome things can happen. 
One awesome thing that can happen then: When someone in the Card Creator selects Heal THIS in the Card Creator while creating an Action card, the Card Creator could check if the card type (Action) fits to the Targets, which would not include Action in the case of Heal. Or even more awesome just don't display the THIS option in the first place, because it won't work anyway.

It might also be desirable to put valid Cardtypes on abilities as well, so that you cannot put Trample on a HQ or a Place (see #83), similar things apply for Loot (I guess a place cannot go to the enemy and loot stuff if your forces breakthrough). And also OnDeath might not be so useful for HQs (except in Multiplayer games with more than 2 players :D)

This can also be realized as an optional thing, so the current Target stays and there are just a few more extra Target types, which exclude things like HQ or Place or both.

**Comment by patrickwieth** [comment]
Effects affected:
Arm (only E)
Armor (only E)
Bounce (only E, but debate if Places should be included exists)
Burn (only HP)
CountPower (only E)
Fortify (only H)
Grind (only HP)
Harm (only E)
Hasten (only E)
Heal (only E)
Kill (only E)
Reassemble (only P) 
Ressurect (only E)
Repair (only HP)
Sacrifice (only E)
Silence (only E)
Suffer (only E)
Strengthen (only E)
Train (only E)
Withdraw (only E)

Abilities affected:
- Trample (only E)
- OnDeath (no HQ)
- Dismantle (only P)
- Tribute (only E)
- Loot (debatable)

**Comment by patrickwieth** [comment]
Update:
Loot debate is settled. It can be on all cards, even HQs. 

Please consider if this here should be in the next blockchain upgrade.

**Comment by nlsui** [comment]
So basicly for every effect add an attribute which tells which card types can be affected by it?

**Comment by patrickwieth** [comment]
> 

yes that would work

Discount was forgotten here and added to the list above
