### ISSUE TITLE
unexpected end of JSON input

### ISSUE THREAD

**Issue by patrickwieth** [DecentralCardGame/cardobject#97]
when reading a genesis.json with the cards, each card gives this error:

![image](https://github.com/DecentralCardGame/cardobject/assets/10943178/4855dc7e-540e-4ad3-a2bb-751c9abe644c)

it does not affect functionality, but we should still fix this, so that the error log becomes more meaningful and validators are not confused (thinking the chain might be broken). This is not high priority, but should be done before launch.

**Comment by nlsui** [comment]
without the json I cannot find the error.
also insight a single cardobject there should not be such errors,
since they would likely produce the same error insight the cardobject tests

**Comment by patrickwieth** [comment]
Hmm, I guess the error we are seeing comes from here:
https://github.com/DecentralCardGame/Cardchain/blob/master/x/cardchain/genesis.go#L50

Maybe we are not properly closing the json file?

**Comment by patrickwieth** [comment]
But then it should be somehwere here:
https://github.com/DecentralCardGame/cardobject/blob/master/keywords/unmarshal.go ?

**Comment by nlsui** [comment]
can I close this or does the problem still exist?

**Comment by patrickwieth** [comment]
does still exist

**Comment by nlsui** [comment]
then I need more description. Is the broken json evailable? do we know which cards could be broken?

**Comment by patrickwieth** [comment]
the error comes from unescaped " in json, should use ' or \" 
example:
"Keywords":["["Tribute","Burn","Insight"]"],

**Comment by nlsui** [comment]
can not be fixed in cardobject, patrick will fix it in frontend
